language: java

before_deploy: gradle makeArchives

arch:
  - amd64
  - arm64

deploy:
  provider: releases
  api_key: KBpdsl2-BiX2uNJe6d1OnA
  file:
     - "brunel-all.tar.gz"
     - "brunel-all.zip"
  skip_cleanup: true
  on:
    repo: Brunel-Visualization/Brunel
    tags: true
