language: java

jdk: openjdk8

arch:
  - amd64
  - arm64

before_deploy: gradle makeArchives

install:
  - sudo apt-get -y install openjdk-8-jdk wget zip unzip
  - curl -s "https://get.sdkman.io" | bash
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - sdk install gradle
  
deploy:
  provider: releases
  api_key: KBpdsl2-BiX2uNJe6d1OnA
  file:
     - "brunel-all.tar.gz"
     - "brunel-all.zip"
  skip_cleanup: true
  on:
    repo: Brunel-Visualization/Brunel
    tags: true
