language: java

jdk: openjdk8

arch:
  - amd64
  - arm64

before_deploy: gradle makeArchives

install:
  - sudo apt-get install openjdk-8-jdk
  - sdk install gradle 6.6.1
deploy:
  provider: releases
  api_key: KBpdsl2-BiX2uNJe6d1OnA
  file:
     - "brunel-all.tar.gz"
     - "brunel-all.zip"
  skip_cleanup: true
  on:
    repo: Brunel-Visualization/Brunel
    tags: true
